import type {
  AdvancedChatKaiProps,
  ChatMessageAttachment,
  ChatMessageReply,
  ChatMessageSuggestion,
  ChatRoom,
  ChatItemType,
  Dialog,
  I18nType,
} from "../types";

export const rooms: ChatRoom[] = [
  {
    id: "support-ticket-1234",
    headerTitle: "Support: Order #1234",
    headerSubtitle: "Shipping inquiry",
    sidebarTitle: "Order #1234",
    sidebarSubtitle: "Shipping inquiry",
    avatar: "https://api.dicebear.com/7.x/initials/svg?seed=CS",
    meta: "2 min ago",
    badge: { label: "Active", type: "success" },
    hasEnded: false,
  },
  {
    id: "team-chat",
    headerTitle: "Engineering Team",
    headerSubtitle: "5 members",
    sidebarTitle: "Engineering Team",
    sidebarSubtitle: "Alex: Let's sync up tomorrow",
    avatar: "https://api.dicebear.com/7.x/initials/svg?seed=ET",
    meta: "1 hour ago",
    badge: { label: "3", type: "info" },
    hasEnded: false,
  },
  {
    id: "sales-lead",
    headerTitle: "Acme Corp",
    headerSubtitle: "Enterprise lead",
    sidebarTitle: "Acme Corp",
    sidebarSubtitle: "Thanks for the proposal!",
    avatar: "https://api.dicebear.com/7.x/initials/svg?seed=AC",
    meta: "Yesterday",
    hasEnded: false,
  },
  {
    id: "urgent-ticket",
    headerTitle: "Support: Payment Failed",
    headerSubtitle: "Urgent",
    sidebarTitle: "Payment Failed",
    sidebarSubtitle: "Customer unable to checkout",
    avatar: "https://api.dicebear.com/7.x/initials/svg?seed=PF",
    meta: "30 min ago",
    badge: { label: "Urgent", type: "warning" },
    hasEnded: false,
  },
  {
    id: "closed-ticket",
    headerTitle: "Support: Refund Request",
    headerSubtitle: "Resolved",
    sidebarTitle: "Refund Request",
    sidebarSubtitle: "Issue resolved",
    avatar: "https://api.dicebear.com/7.x/initials/svg?seed=RR",
    meta: "3 days ago",
    badge: { label: "Closed", type: "danger" },
    hasEnded: true,
  },
];

export const messages: ChatItemType[] = [
  {
    id: "divider-today",
    type: "divider",
    roomId: "support-ticket-1234",
    content: "Today",
  },
   {
    id: "msg-deleted",
    type: "message",
    roomId: "support-ticket-1234",
    senderId: "customer-jane",
    senderName: "Jane Smith",
    senderAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Jane",
    content: "This message was deleted",
    timestamp: "10:29 AM",
    reactions: {},
    attachments: [],
    isDeleted: true,
    isSelected: false,
    replyTo: null,
  },
  {
    id: "msg-1",
    type: "message",
    roomId: "support-ticket-1234",
    senderId: "customer-jane",
    senderName: "Jane Smith",
    senderAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Jane",
    content: "Hi! I placed an order yesterday but haven't received a tracking number yet. Order #1234.",
    timestamp: "10:23 AM",
    reactions: {},
    attachments: [],
    isDeleted: false,
    isSelected: false,
    replyTo: null,
  },
  {
    id: "msg-2",
    type: "message",
    roomId: "support-ticket-1234",
    senderId: "current-user-id",
    senderName: "Support Agent",
    senderAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Agent",
    content: "Hello Jane! Let me look into that for you. One moment please.",
    timestamp: "10:25 AM",
    reactions: { "👍": ["customer-jane"] },
    attachments: [],
    isDeleted: false,
    isSelected: false,
    replyTo: null,
  },
  {
    id: "msg-3",
    type: "message",
    roomId: "support-ticket-1234",
    senderId: "current-user-id",
    senderName: "Support Agent",
    senderAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Agent",
    content: "I found your order! It shipped this morning. Here's your tracking information:",
    timestamp: "10:27 AM",
    reactions: {},
    attachments: [
      {
        id: "tracking-doc",
        name: "tracking-info.pdf",
        meta: "145 KB",
      },
    ],
    isDeleted: false,
    isSelected: false,
    replyTo: null,
  },
  {
    id: "msg-4",
    type: "message",
    roomId: "support-ticket-1234",
    senderId: "customer-jane",
    senderName: "Jane Smith",
    senderAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Jane",
    content: "That's great, thank you so much! 🎉",
    timestamp: "10:28 AM",
    reactions: {
      "❤️": ["current-user-id", "team-member-1"],
      "🎉": ["current-user-id", "team-member-1", "team-member-2"],
      "👏": ["team-member-2"],
    },
    attachments: [],
    isDeleted: false,
    isSelected: false,
    replyTo: null,
  },
];

export const messageWithReply: ChatItemType = {
  id: "reply-msg",
  type: "message",
  roomId: "support-ticket-1234",
  senderId: "current-user-id",
  senderName: "Support Agent",
  senderAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Agent",
  content: "Yes, that tracking number is correct!",
  timestamp: "10:30 AM",
  reactions: {},
  attachments: [],
  isDeleted: false,
  isSelected: false,
  replyTo: {
    id: "msg-4",
    type: "message",
    roomId: "support-ticket-1234",
    senderId: "customer-jane",
    senderName: "Jane Smith",
    senderAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Jane",
    content: "Is this tracking number correct?",
    timestamp: "10:29 AM",
    reactions: {},
    attachments: [],
    isDeleted: false,
    isSelected: false,
  },
};

export const messageWithImages: ChatItemType = {
  id: "image-msg",
  type: "message",
  roomId: "support-ticket-1234",
  senderId: "customer-jane",
  senderName: "Jane Smith",
  senderAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Jane",
  content: "Here are the screenshots of the issue:",
  timestamp: "10:31 AM",
  reactions: {},
  attachments: [
    {
      id: "screenshot-1",
      name: "error-screen.png",
      meta: "1.2 MB",
      imageUrl: "https://placehold.co/400x300/e2e8f0/64748b?text=Screenshot+1",
    },
    {
      id: "screenshot-2",
      name: "console-log.png",
      meta: "890 KB",
      imageUrl: "https://placehold.co/400x300/e2e8f0/64748b?text=Screenshot+2",
    },
  ],
  isDeleted: false,
  isSelected: false,
  replyTo: null,
};

export const attachments: ChatMessageAttachment[] = [
  { id: "att-1", name: "invoice.pdf", meta: "256 KB" },
  { id: "att-2", name: "photo.jpg", meta: "1.8 MB", imageUrl: "https://placehold.co/200x150/e2e8f0/64748b?text=Photo" },
];

export const suggestions: ChatMessageSuggestion[] = [
  { text: "Check order status", value: "check-status" },
  { text: "Request refund", value: "request-refund" },
  { text: "Talk to agent", value: "talk-agent" },
];

export const replyTo: ChatMessageReply = {
  id: "msg-1",
  type: "message",
  roomId: "support-ticket-1234",
  senderId: "customer-jane",
  senderName: "Jane Smith",
  senderAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Jane",
  content: "Hi! I placed an order yesterday but haven't received a tracking number yet.",
  timestamp: "10:23 AM",
  reactions: {},
  attachments: [],
  isDeleted: false,
  isSelected: false,
};

export const confirmDialog: Dialog = {
  event: "close-conversation",
  body: "Are you sure you want to close this conversation? The customer will be notified.",
  leftButton: { text: "Cancel" },
  rightButton: { text: "Close", variant: "danger" },
};

export const localizedText: I18nType = {
  DELETED_MESSAGE: "このメッセージは削除されました",
  CHAT_SEARCH_PLACEHOLDER: "会話を検索...",
  CHAT_FOOTER_TEXTAREA_PLACEHOLDER: "メッセージを入力...",
  CLOSED_ROOM_MESSAGE: "この会話は終了しました",
  NEW_MESSAGE_NOTIFICATION: "新着メッセージがあります",
};

export const roomActions = [
  { label: "Mark as read", value: "mark-read" },
  { label: "Archive", value: "archive" },
  { label: "Delete", value: "delete" },
];

export const myMessageActions = [
  { label: "Edit", value: "edit" },
  { label: "Copy", value: "copy" },
  { label: "Delete", value: "delete" },
];

export const theirMessageActions = [
  { label: "Reply", value: "reply" },
  { label: "Copy", value: "copy" },
  { label: "Report", value: "report" },
];

const baseProps: Partial<AdvancedChatKaiProps> = {
  currentUserId: "current-user-id",
  height: "600px",
  width: "900px",
  theme: "light",
  showRoomAvatar: true,
  showTheirAvatar: true,
  isEmojiPickerAvailable: true,
  isEmojiReactionAvailable: true,
  isReplyAvailable: true,
  isMessageAttachmentAvailable: true,
  roomActions,
  myMessageActions,
  theirMessageActions,
};

/** Standard chat with active conversation */
export const activeChat: AdvancedChatKaiProps = {
  ...baseProps,
  rooms,
  messages,
  selectedRoomId: "support-ticket-1234",
};

/** Empty state */
export const emptyState: AdvancedChatKaiProps = {
  ...baseProps,
  rooms: [],
  messages: [],
  selectedRoomId: null,
};

/** Loading state */
export const loadingState: AdvancedChatKaiProps = {
  ...baseProps,
  rooms: [],
  messages: [],
  isLoadingRoom: true,
  isLoadingMessage: true,
};

/** Mobile layout */
export const mobileLayout: AdvancedChatKaiProps = {
  ...activeChat,
  isMobile: true,
  width: "375px",
  height: "667px",
};

/** Single room mode */
export const singleRoomMode: AdvancedChatKaiProps = {
  ...activeChat,
  isSingleRoom: true,
  width: "600px",
};

/** Edge case fixtures for comprehensive layout testing */
export const edgeCaseRooms: ChatRoom[] = [
  {
    id: "edge-case-room",
    headerTitle: "Very Long Room Title That Should Be Truncated When It Exceeds The Available Width",
    headerSubtitle: "This is an extremely long subtitle that contains a lot of information and should definitely be truncated",
    sidebarTitle: "Long Sidebar Title That Gets Cut Off",
    sidebarSubtitle: "This sidebar subtitle is also very long and needs truncation to fit properly in the room list",
    avatar: "https://api.dicebear.com/7.x/initials/svg?seed=EC",
    meta: "2 min ago",
    badge: { label: "In Progress - Waiting For Review", type: "warning" },
    hasEnded: false,
  },
  {
    id: "short-room",
    headerTitle: "Q&A",
    headerSubtitle: "Help",
    sidebarTitle: "Q&A",
    sidebarSubtitle: "Hi",
    avatar: "https://api.dicebear.com/7.x/initials/svg?seed=QA",
    meta: "1h",
    badge: { label: "1", type: "info" },
    hasEnded: false,
  },
  // Many rooms to demonstrate scrollbar
  {
    id: "room-3",
    headerTitle: "Support Ticket #3",
    headerSubtitle: "Active",
    sidebarTitle: "Support Ticket #3",
    sidebarSubtitle: "Looking into the issue now",
    avatar: "https://api.dicebear.com/7.x/initials/svg?seed=S3",
    meta: "5 min ago",
    badge: { label: "Active", type: "success" },
    hasEnded: false,
  },
  {
    id: "room-4",
    headerTitle: "Sales Lead - Enterprise",
    headerSubtitle: "2 members",
    sidebarTitle: "Sales Lead",
    sidebarSubtitle: "Proposal sent",
    avatar: "https://api.dicebear.com/7.x/initials/svg?seed=SL",
    meta: "10 min ago",
    hasEnded: false,
  },
  {
    id: "room-5",
    headerTitle: "Bug Report #42",
    headerSubtitle: "Engineering",
    sidebarTitle: "Bug #42",
    sidebarSubtitle: "CSS layout broken on mobile",
    avatar: "https://api.dicebear.com/7.x/initials/svg?seed=B4",
    meta: "30 min ago",
    badge: { label: "Bug", type: "danger" },
    hasEnded: false,
  },
  {
    id: "room-6",
    headerTitle: "Customer Feedback",
    headerSubtitle: "Review",
    sidebarTitle: "Customer Feedback",
    sidebarSubtitle: "Great experience overall!",
    avatar: "https://api.dicebear.com/7.x/initials/svg?seed=CF",
    meta: "1h ago",
    hasEnded: false,
  },
  {
    id: "room-7",
    headerTitle: "Feature Request",
    headerSubtitle: "Backlog",
    sidebarTitle: "Feature Request",
    sidebarSubtitle: "Dark mode toggle",
    avatar: "https://api.dicebear.com/7.x/initials/svg?seed=FR",
    meta: "2h ago",
    badge: { label: "New", type: "info" },
    hasEnded: false,
  },
  {
    id: "room-8",
    headerTitle: "Team Standup",
    headerSubtitle: "Daily",
    sidebarTitle: "Team Standup",
    sidebarSubtitle: "Tomorrow at 10am",
    avatar: "https://api.dicebear.com/7.x/initials/svg?seed=TS",
    meta: "3h ago",
    hasEnded: false,
  },
  {
    id: "room-9",
    headerTitle: "Billing Question",
    headerSubtitle: "Finance",
    sidebarTitle: "Billing Question",
    sidebarSubtitle: "Invoice #5678",
    avatar: "https://api.dicebear.com/7.x/initials/svg?seed=BQ",
    meta: "Yesterday",
    hasEnded: false,
  },
  {
    id: "room-10",
    headerTitle: "Integration Help",
    headerSubtitle: "API Support",
    sidebarTitle: "Integration Help",
    sidebarSubtitle: "Webhook setup",
    avatar: "https://api.dicebear.com/7.x/initials/svg?seed=IH",
    meta: "Yesterday",
    badge: { label: "Waiting", type: "warning" },
    hasEnded: false,
  },
  {
    id: "room-11",
    headerTitle: "Onboarding",
    headerSubtitle: "New Customer",
    sidebarTitle: "Onboarding",
    sidebarSubtitle: "Welcome call scheduled",
    avatar: "https://api.dicebear.com/7.x/initials/svg?seed=OB",
    meta: "2 days ago",
    hasEnded: false,
  },
  {
    id: "room-12",
    headerTitle: "Archived Chat",
    headerSubtitle: "Closed",
    sidebarTitle: "Archived Chat",
    sidebarSubtitle: "Issue resolved - closed",
    avatar: "https://api.dicebear.com/7.x/initials/svg?seed=AC",
    meta: "1 week ago",
    badge: { label: "Closed", type: "danger" },
    hasEnded: true,
  },
];

export const edgeCaseMessages: ChatItemType[] = [
  {
    id: "divider-edge",
    type: "divider",
    roomId: "edge-case-room",
    content: "Edge Cases Demo",
  },

  // === Short message - single emoji (both sides) ===
  {
    id: "edge-msg-short-emoji-theirs",
    type: "message",
    roomId: "edge-case-room",
    senderId: "customer-edge",
    senderName: "Jane",
    senderAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Jane",
    content: "👋",
    timestamp: "10:00 AM",
    reactions: {},
    attachments: [],
    isDeleted: false,
    isSelected: false,
    replyTo: null,
  },
  {
    id: "edge-msg-short-emoji-mine",
    type: "message",
    roomId: "edge-case-room",
    senderId: "current-user-id",
    senderName: "Agent",
    senderAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Agent",
    content: "👍",
    timestamp: "10:00 AM",
    reactions: {},
    attachments: [],
    isDeleted: false,
    isSelected: false,
    replyTo: null,
  },

  // === Very short text (both sides) ===
  {
    id: "edge-msg-short-text-theirs",
    type: "message",
    roomId: "edge-case-room",
    senderId: "customer-edge",
    senderName: "Jane",
    senderAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Jane",
    content: "ok",
    timestamp: "10:01 AM",
    reactions: {
      "👍": ["current-user-id"],
    },
    attachments: [],
    isDeleted: false,
    isSelected: false,
    replyTo: null,
  },
  {
    id: "edge-msg-short-text-mine",
    type: "message",
    roomId: "edge-case-room",
    senderId: "current-user-id",
    senderName: "Agent",
    senderAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Agent",
    content: "k",
    timestamp: "10:01 AM",
    reactions: {
      "👍": ["customer-edge"],
    },
    attachments: [],
    isDeleted: false,
    isSelected: false,
    replyTo: null,
  },

  // === Short text with many reactions (both sides) ===
  {
    id: "edge-msg-short-many-reactions-theirs",
    type: "message",
    roomId: "edge-case-room",
    senderId: "customer-edge",
    senderName: "Jane",
    senderAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Jane",
    content: "Thanks!",
    timestamp: "10:02 AM",
    reactions: {
      "👍": ["current-user-id", "user-1", "user-2", "user-3", "user-4"],
      "❤️": ["user-1", "user-2", "user-3", "user-4", "user-5"],
      "🎉": ["current-user-id", "user-1", "user-2"],
      "😂": ["user-3", "user-4"],
      "🔥": ["user-5", "user-6"],
      "👀": ["current-user-id"],
      "✨": ["user-1", "user-2", "user-3"],
      "💯": ["user-4", "user-5"],
    },
    attachments: [],
    isDeleted: false,
    isSelected: false,
    replyTo: null,
  },
  {
    id: "edge-msg-short-many-reactions-mine",
    type: "message",
    roomId: "edge-case-room",
    senderId: "current-user-id",
    senderName: "Agent",
    senderAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Agent",
    content: "You're welcome!",
    timestamp: "10:02 AM",
    reactions: {
      "👍": ["customer-edge", "user-1", "user-2", "user-3"],
      "❤️": ["customer-edge", "user-1", "user-2"],
      "🎉": ["user-1", "user-2", "user-3"],
      "😂": ["user-4", "user-5"],
      "🔥": ["user-6"],
      "👀": ["customer-edge", "user-7"],
      "✨": ["user-1", "user-2"],
      "💯": ["user-3", "user-4"],
    },
    attachments: [],
    isDeleted: false,
    isSelected: false,
    replyTo: null,
  },

  // === Long message with many reactions (both sides) ===
  {
    id: "edge-msg-long-many-reactions-theirs",
    type: "message",
    roomId: "edge-case-room",
    senderId: "customer-long-name",
    senderName: "Alexandra Elizabeth Montgomery-Fitzgerald III",
    senderAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Long",
    content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
    timestamp: "10:05 AM",
    reactions: {
      "👍": ["current-user-id", "user-1", "user-2", "user-3", "user-4", "user-5", "user-6", "user-7", "user-8", "user-9"],
      "❤️": ["user-1", "user-2", "user-3"],
      "🎉": ["current-user-id", "user-1"],
      "😂": ["user-2", "user-3", "user-4"],
      "🔥": ["user-5"],
      "👀": ["current-user-id", "user-6", "user-7"],
    },
    attachments: [],
    isDeleted: false,
    isSelected: false,
    replyTo: null,
  },
  {
    id: "edge-msg-long-many-reactions-mine",
    type: "message",
    roomId: "edge-case-room",
    senderId: "current-user-id",
    senderName: "Support Agent",
    senderAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Agent",
    content: "Thank you for your detailed message. I've reviewed all the points you mentioned and I want to address each one thoroughly. Let me go through them systematically to ensure we cover everything and provide you with the most comprehensive response possible.",
    timestamp: "10:06 AM",
    reactions: {
      "👍": ["customer-long-name", "user-1", "user-2", "user-3", "user-4"],
      "❤️": ["customer-long-name", "user-1"],
      "🎉": ["user-2", "user-3"],
      "✨": ["user-4", "user-5"],
    },
    attachments: [],
    isDeleted: false,
    isSelected: false,
    replyTo: null,
  },

  // === Many attachments (both sides) ===
  {
    id: "edge-msg-many-attachments-theirs",
    type: "message",
    roomId: "edge-case-room",
    senderId: "customer-edge",
    senderName: "Jane",
    senderAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Jane",
    content: "Here are my files:",
    timestamp: "10:10 AM",
    reactions: {},
    attachments: [
      {
        id: "edge-att-theirs-1",
        name: "super-long-filename-that-needs-truncation-invoice-2024-q4-final.pdf",
        meta: "1.8 MB",
      },
      {
        id: "edge-att-theirs-2",
        name: "data.xlsx",
        meta: "256 KB",
      },
      {
        id: "edge-att-theirs-3",
        name: "issue-screenshot.png",
        meta: "1.2 MB",
        imageUrl: "https://placehold.co/400x300/e2e8f0/64748b?text=Issue",
      },
    ],
    isDeleted: false,
    isSelected: false,
    replyTo: null,
  },
  {
    id: "edge-msg-many-attachments-mine",
    type: "message",
    roomId: "edge-case-room",
    senderId: "current-user-id",
    senderName: "Support Agent",
    senderAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Agent",
    content: "Here are all the requested files:",
    timestamp: "10:11 AM",
    reactions: {},
    attachments: [
      {
        id: "edge-att-mine-1",
        name: "extremely-long-filename-that-should-be-truncated-with-ellipsis-2024-final-v2-revised.pdf",
        meta: "2.5 MB",
      },
      {
        id: "edge-att-mine-2",
        name: "report.xlsx",
        meta: "456 KB",
      },
      {
        id: "edge-att-mine-3",
        name: "contract-draft.docx",
        meta: "1.2 MB",
      },
      {
        id: "edge-att-mine-4",
        name: "screenshot.png",
        meta: "890 KB",
        imageUrl: "https://placehold.co/400x300/e2e8f0/64748b?text=Screenshot",
      },
      {
        id: "edge-att-mine-5",
        name: "photo.jpg",
        meta: "1.5 MB",
        imageUrl: "https://placehold.co/300x400/e2e8f0/64748b?text=Photo",
      },
    ],
    isDeleted: false,
    isSelected: false,
    replyTo: null,
  },

  // === Deleted message (both sides) ===
  {
    id: "edge-msg-deleted-theirs",
    type: "message",
    roomId: "edge-case-room",
    senderId: "customer-edge",
    senderName: "Jane",
    senderAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Jane",
    content: "This message was deleted",
    timestamp: "10:12 AM",
    reactions: {},
    attachments: [],
    isDeleted: true,
    isSelected: false,
    replyTo: null,
  },
  {
    id: "edge-msg-deleted-mine",
    type: "message",
    roomId: "edge-case-room",
    senderId: "current-user-id",
    senderName: "Agent",
    senderAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Agent",
    content: "This message was deleted",
    timestamp: "10:12 AM",
    reactions: {},
    attachments: [],
    isDeleted: true,
    isSelected: false,
    replyTo: null,
  },

  // === Selected/highlighted message (both sides) ===
  {
    id: "edge-msg-selected-theirs",
    type: "message",
    roomId: "edge-case-room",
    senderId: "customer-edge",
    senderName: "Jane",
    senderAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Jane",
    content: "This message is selected (their side).",
    timestamp: "10:15 AM",
    reactions: {
      "✅": ["current-user-id"],
    },
    attachments: [],
    isDeleted: false,
    isSelected: true,
    replyTo: null,
  },
  {
    id: "edge-msg-selected-mine",
    type: "message",
    roomId: "edge-case-room",
    senderId: "current-user-id",
    senderName: "Agent",
    senderAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Agent",
    content: "This message is selected (my side).",
    timestamp: "10:15 AM",
    reactions: {
      "✅": ["customer-edge"],
    },
    attachments: [],
    isDeleted: false,
    isSelected: true,
    replyTo: null,
  },

  // === Multi-paragraph message (both sides) ===
  {
    id: "edge-msg-multiline-theirs",
    type: "message",
    roomId: "edge-case-room",
    senderId: "customer-edge",
    senderName: "Jane",
    senderAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Jane",
    content: "First paragraph from customer.\n\nSecond paragraph continues.\n\nThird paragraph ends.",
    timestamp: "10:20 AM",
    reactions: {},
    attachments: [],
    isDeleted: false,
    isSelected: false,
    replyTo: null,
  },
  {
    id: "edge-msg-multiline-mine",
    type: "message",
    roomId: "edge-case-room",
    senderId: "current-user-id",
    senderName: "Agent",
    senderAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Agent",
    content: "First paragraph from agent.\n\nSecond paragraph with more details.\n\nThird paragraph wraps up.",
    timestamp: "10:21 AM",
    reactions: {},
    attachments: [],
    isDeleted: false,
    isSelected: false,
    replyTo: null,
  },

  // === Reply to long message (both sides) ===
  {
    id: "edge-msg-reply-to-long-theirs",
    type: "message",
    roomId: "edge-case-room",
    senderId: "customer-edge",
    senderName: "Jane",
    senderAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Jane",
    content: "Thanks for addressing all those points!",
    timestamp: "10:25 AM",
    reactions: {},
    attachments: [],
    isDeleted: false,
    isSelected: false,
    replyTo: {
      id: "edge-msg-long-many-reactions-mine",
      type: "message",
      roomId: "edge-case-room",
      senderId: "current-user-id",
      senderName: "Support Agent",
      senderAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Agent",
      content: "Thank you for your detailed message. I've reviewed all the points you mentioned and I want to address each one thoroughly.",
      timestamp: "10:06 AM",
      reactions: {},
      attachments: [],
      isDeleted: false,
      isSelected: false,
    },
  },
  {
    id: "edge-msg-reply-to-long-mine",
    type: "message",
    roomId: "edge-case-room",
    senderId: "current-user-id",
    senderName: "Support Agent",
    senderAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Agent",
    content: "Regarding your detailed message - I'll address each point.",
    timestamp: "10:26 AM",
    reactions: {},
    attachments: [],
    isDeleted: false,
    isSelected: false,
    replyTo: {
      id: "edge-msg-long-many-reactions-theirs",
      type: "message",
      roomId: "edge-case-room",
      senderId: "customer-long-name",
      senderName: "Alexandra Elizabeth Montgomery-Fitzgerald III",
      senderAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Long",
      content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      timestamp: "10:05 AM",
      reactions: {},
      attachments: [],
      isDeleted: false,
      isSelected: false,
    },
  },

  // === Long unbreakable text/URL (both sides) ===
  {
    id: "edge-msg-long-url-theirs",
    type: "message",
    roomId: "edge-case-room",
    senderId: "customer-edge",
    senderName: "Jane",
    senderAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Jane",
    content: "Check this link: https://example.com/very-long-url-path/that-should-wrap-properly/without-overflowing/the-message-container/parameters?query=superlongquerystringwithoutanyspaces&token=abc123xyz789",
    timestamp: "10:30 AM",
    reactions: {},
    attachments: [],
    isDeleted: false,
    isSelected: false,
    replyTo: null,
  },
  {
    id: "edge-msg-long-url-mine",
    type: "message",
    roomId: "edge-case-room",
    senderId: "current-user-id",
    senderName: "Agent",
    senderAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Agent",
    content: "Here's the documentation: https://documentation.example.com/api/v2/reference/endpoints/users/authentication/oauth2/callback?redirect_uri=https://app.example.com/auth&client_id=1234567890abcdef",
    timestamp: "10:31 AM",
    reactions: {},
    attachments: [],
    isDeleted: false,
    isSelected: false,
    replyTo: null,
  },
];

/** Edge cases layout testing */
export const edgeCasesChat: AdvancedChatKaiProps = {
  ...baseProps,
  rooms: edgeCaseRooms,
  messages: edgeCaseMessages,
  selectedRoomId: "edge-case-room",
};

