import { AdvancedChatKai } from "../components/advanced-chat-kai";
import { ChatActionList } from "../components/chat-action-list";
import { ChatAvatar } from "../components/chat-avatar";
import { ChatContainer } from "../components/chat-container";
import { ChatDeletedMessage } from "../components/chat-deleted-message";
import { ChatDialog } from "../components/chat-dialog";
import { ChatEmojiPicker } from "../components/chat-emoji-picker";
import { ChatFooterAttachmentSection } from "../components/chat-footer-attachment-section";
import { ChatFooterReplyToSection } from "../components/chat-footer-reply-to-section";
import { ChatFooter } from "../components/chat-footer";
import { ChatHeader } from "../components/chat-header";
import { ChatLoader } from "../components/chat-loader";
import { ChatMessageAttachmentList } from "../components/chat-message-attachment-list";
import { ChatMessageDivider } from "../components/chat-message-divider";
import { ChatMessageItem } from "../components/chat-message-item";
import { ChatMessageList } from "../components/chat-message-list";
import { ChatMessageMenu } from "../components/chat-message-menu";
import { ChatMessageReactionList } from "../components/chat-message-reaction-list";
import { ChatMessageReplyTo } from "../components/chat-message-reply-to";
import { ChatMessageTyping } from "../components/chat-message-typing";
import { ChatNotificationBadge } from "../components/chat-notification-badge";
import { ChatRoomItem } from "../components/chat-room-item";
import { ChatRoomList } from "../components/chat-room-list";
import { ChatSearch } from "../components/chat-search";
import { ChatSidebar } from "../components/chat-sidebar";
import { ChatSuggestionList } from "../components/chat-suggestion-list";

customElements.define("advanced-chat-kai", AdvancedChatKai);
customElements.define("chat-action-list", ChatActionList);
customElements.define("chat-avatar", ChatAvatar);
customElements.define("chat-container", ChatContainer);
customElements.define("chat-deleted-message", ChatDeletedMessage);
customElements.define("chat-dialog", ChatDialog);
customElements.define("chat-emoji-picker", ChatEmojiPicker);
customElements.define("chat-footer-attachment-section", ChatFooterAttachmentSection);
customElements.define("chat-footer-reply-to-section", ChatFooterReplyToSection);
customElements.define("chat-footer", ChatFooter);
customElements.define("chat-header", ChatHeader);
customElements.define("chat-loader", ChatLoader);
customElements.define("chat-message-divider", ChatMessageDivider);
customElements.define("chat-message-attachment-list", ChatMessageAttachmentList);
customElements.define("chat-message-item", ChatMessageItem);
customElements.define("chat-message-list", ChatMessageList);
customElements.define("chat-message-menu", ChatMessageMenu);
customElements.define("chat-message-reaction-list", ChatMessageReactionList);
customElements.define("chat-message-reply-to", ChatMessageReplyTo);
customElements.define("chat-message-typing", ChatMessageTyping);
customElements.define("chat-notification-badge", ChatNotificationBadge);
customElements.define("chat-room-item", ChatRoomItem);
customElements.define("chat-room-list", ChatRoomList);
customElements.define("chat-search", ChatSearch);
customElements.define("chat-sidebar", ChatSidebar);
customElements.define("chat-suggestion-list", ChatSuggestionList);
