import type { AdvancedChatKaiProps } from "../src/types";

export const defaultProps: AdvancedChatKaiProps = {
  currentUserId: "1",
  rooms: [
    {
      id: "1",
      headerTitle: "Room 1",
      headerSubtitle: "Subtitle 1",
      sidebarTitle: "Room 1",
      sidebarSubtitle: "Subtitle 1",
      avatar: `/lit.svg`,
      meta: "May 1",
      badge: {
        type: "success",
        label: "Success",
      },
      hasEnded: false,
    },
    {
      id: "2",
      headerTitle:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
      headerSubtitle:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
      sidebarTitle:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
      sidebarSubtitle:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
      avatar: "/lit.svg",
      meta: "May 1",
      badge: {
        type: "danger",
        label: "Danger",
      },
      hasEnded: false,
    },
    {
      id: "3",
      headerTitle: "Room 3",
      headerSubtitle: "Subtitle 3",
      sidebarTitle: "Room 3",
      sidebarSubtitle: "Subtitle 3",
      avatar: "/lit.svg",
      meta: "May 1",
      badge: {
        type: "warning",
        label: "Warning",
      },
      hasEnded: false,
    },
    {
      id: "4",
      headerTitle: "Room 4",
      headerSubtitle: "Subtitle 4",
      sidebarTitle: "Room 4",
      sidebarSubtitle: "Subtitle 4",
      avatar: "/lit.svg",
      meta: "May 1",
      badge: {
        type: "info",
        label: "Info",
      },
      hasEnded: false,
    },
    {
      id: "5",
      headerTitle: "Room 5",
      headerSubtitle: "Subtitle 5",
      sidebarTitle: "Subtitle 5",
      sidebarSubtitle: "Subtitle 5",
      avatar: "/lit.svg",
      meta: "May 1",
      badge: {
        type: "success",
        label: "",
      },
      hasEnded: false,
    },
    {
      id: "6",
      headerTitle: "Room 6",
      headerSubtitle: "Subtitle 6",
      sidebarTitle: "Room 6",
      sidebarSubtitle: "Subtitle 6",
      avatar: "/lit.svg",
      meta: "May 1",
      badge: {
        type: "danger",
        label: "",
      },
      hasEnded: false,
    },
    {
      id: "7",
      headerTitle: "Room 7",
      headerSubtitle: "Subtitle 7",
      sidebarTitle: "Room 7",
      sidebarSubtitle: "Subtitle 7",
      avatar: "/lit.svg",
      meta: "May 1",
      badge: {
        type: "warning",
        label: "",
      },
      hasEnded: false,
    },
    {
      id: "8",
      headerTitle: "Room 8",
      headerSubtitle: "Subtitle 8",
      sidebarTitle: "Room 8",
      sidebarSubtitle: "Subtitle 8",
      avatar: "/lit.svg",
      meta: "May 1",
      badge: {
        type: "info",
        label: "",
      },
      hasEnded: false,
    },
    {
      id: "9",
      headerTitle: "Room 9",
      headerSubtitle: "Subtitle 9",
      sidebarTitle: "Room 9",
      sidebarSubtitle: "Subtitle 9",
      avatar: "/lit.svg",
      meta: "May 1",
      hasEnded: false,
    },
    {
      id: "10",
      headerTitle: "Room 10",
      headerSubtitle: "Subtitle 10",
      sidebarTitle: "Room 10",
      sidebarSubtitle: "Subtitle 10",
      avatar: "/lit.svg",
      meta: "May 1",
      hasEnded: false,
    },
  ],
  messages: [
    {
      id: "0",
      type: "divider",
      content: "May 1",
    },
    {
      id: "1",
      type: "message",
      roomId: "1",
      senderId: "1",
      senderName: "User 1",
      senderAvatar: "/lit.svg",
      content: "Hello, how are you?",
      timestamp: "12:34 PM",
      reactions: new Map<string, Set<string>>(),
      attachments: [
        {
          name: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
          meta: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
          id: "file1.txt",
        },
        {
          name: "file2.txt",
          meta: "20 KB",
          id: "file2.txt",
        },
        {
          name: "file3.txt",
          meta: "30 KB",
          id: "file3.txt",
        },
      ],
      isDeleted: false,
      isSelected: false,
      replyTo: null,
    },
    {
      id: "2",
      type: "message",
      roomId: "1",
      senderId: "2",
      senderName: "User 2",
      senderAvatar: "/lit.svg",
      content: "I'm fine, thank you!",
      timestamp: "12:34 PM",
      reactions: new Map<string, Set<string>>(),
      attachments: [
        {
          name: "file1.txt",
          meta: "10 KB",
          id: "file1.txt",
        },
        {
          name: "file2.txt",
          meta: "20 KB",
          id: "file2.txt",
        },
        {
          name: "file3.txt",
          meta: "30 KB",
          id: "file3.txt",
        },
      ],
      isDeleted: false,
      isSelected: false,
      replyTo: null,
    },
    {
      id: "3",
      type: "message",
      roomId: "1",
      senderId: "1",
      senderName: "User 1",
      senderAvatar: "/lit.svg",
      content: "What about you?",
      timestamp: "12:34 PM",
      reactions: new Map<string, Set<string>>(),
      attachments: [],
      isDeleted: false,
      isSelected: false,
      replyTo: null,
    },
    {
      id: "4",
      type: "message",
      roomId: "1",
      senderId: "2",
      senderName: "User 2",
      senderAvatar: "/lit.svg",
      content: "I'm doing great!",
      timestamp: "12:34 PM",
      reactions: new Map<string, Set<string>>(),
      attachments: [],
      isDeleted: false,
      isSelected: false,
      replyTo: null,
    },
    {
      id: "5",
      type: "message",
      roomId: "1",
      senderId: "1",
      senderName: "User 1",
      senderAvatar: "/lit.svg",
      content:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
      timestamp: "12:34 PM",
      reactions: new Map<string, Set<string>>([
        ["😀", new Set(["1", "2"])],
        ["👍", new Set(["3"])],
        ["🎉", new Set(["1", "4", "5"])],
      ]),
      attachments: [],
      isDeleted: false,
      isSelected: false,
      replyTo: null,
    },
    {
      id: "6",
      type: "message",
      roomId: "1",
      senderId: "2",
      senderName:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
      senderAvatar: "/lit.svg",
      content:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
      timestamp: "12:34 PM",
      reactions: new Map<string, Set<string>>([
        ["😀", new Set(["1", "2", "8"])],
        ["👍", new Set(["3", "5", "7"])],
        ["🎉", new Set(["1", "4", "5", "6"])],
        ["❤️", new Set(["2", "3", "6", "9"])],
        ["😂", new Set(["10", "11", "12"])],
        ["😢", new Set(["4"])],
        ["👏", new Set(["2", "6", "8", "10"])],
        ["🔥", new Set(["1", "5", "7", "9"])],
        ["😎", new Set(["3", "8"])],
        ["🙌", new Set(["2", "6", "11"])],
      ]),
      attachments: [],
      isDeleted: false,
      isSelected: false,
      replyTo: null,
    },
    {
      id: "7",
      type: "message",
      roomId: "1",
      senderId: "2",
      senderName: "User 2",
      senderAvatar: "/lit.svg",
      content: "I'm doing great!",
      timestamp: "12:34 PM",
      reactions: new Map<string, Set<string>>(),
      attachments: [],
      isDeleted: true,
      isSelected: false,
      replyTo: null,
    },
    {
      id: "8",
      type: "message",
      roomId: "1",
      senderId: "2",
      senderName: "User 2",
      senderAvatar: "/lit.svg",
      content:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
      timestamp: "12:34 PM",
      reactions: new Map<string, Set<string>>(),
      attachments: [],
      isDeleted: false,
      isSelected: false,
      replyTo: {
        id: "1",
        type: "message",
        roomId: "1",
        senderId: "1",
        senderName: "User 1",
        senderAvatar: "/lit.svg",
        content: "Hello, how are you?",
        timestamp: "12:34 PM",
        reactions: new Map<string, Set<string>>(),
        attachments: [
          {
            name: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
            meta: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
            id: "file1.txt",
          },
          {
            name: "file2.txt",
            meta: "20 KB",
            id: "file2.txt",
          },
          {
            name: "file3.txt",
            meta: "30 KB",
            id: "file3.txt",
          },
        ],
        isDeleted: false,
        isSelected: false,
        replyTo: null,
      },
    },
    {
      id: "9",
      type: "message",
      roomId: "1",
      senderId: "1",
      senderName: "User 1",
      senderAvatar: "/lit.svg",
      content: "***Test markdown***\n\n",
      timestamp: "12:34 PM",
      reactions: new Map<string, Set<string>>(),
      attachments: [],
      isDeleted: false,
      isSelected: false,
      replyTo: null,
    },
    {
      id: "10",
      type: "message",
      roomId: "1",
      senderId: "1",
      senderName: "User 1",
      senderAvatar: "/lit.svg",
      content: "This message is selected",
      timestamp: "12:34 PM",
      reactions: new Map<string, Set<string>>(),
      attachments: [],
      isDeleted: false,
      isSelected: true,
      replyTo: null,
    },
    {
      id: "11",
      type: "message",
      roomId: "1",
      senderId: "2",
      senderName: "User 2",
      senderAvatar: "/lit.svg",
      content: "This message is selected as well",
      timestamp: "12:34 PM",
      reactions: new Map<string, Set<string>>(),
      attachments: [],
      isDeleted: false,
      isSelected: true,
      replyTo: null,
    },
  ],
  suggestions: [
    {
      text: "Hello",
      value: "hello",
    },
    {
      text: "How are you?",
      value: "how-are-you",
    },
    {
      text: "What about you?",
      value: "what-about-you",
    },
    {
      text: "I'm doing great!",
      value: "im-doing-great",
    },
    {
      text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
      value: "lorem-ipsum",
    },
  ],
  attachments: [
    {
      name: "file1.txt",
      meta: "10 KB",
      id: "file1.txt",
    },
    {
      name: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
      meta: "20 KB",
      id: "lorem-ipsum",
    },
    {
      name: "file3.txt",
      meta: "30 KB",
      id: "file3.txt",
    },
    {
      name: "file4.txt",
      meta: "40 KB",
      id: "file4.txt",
    },
    {
      name: "file5.txt",
      meta: "50 KB",
      id: "file5.txt",
    },
    {
      name: "file6.txt",
      meta: "60 KB",
      id: "file6.txt",
    },
    {
      name: "file7.txt",
      meta: "70 KB",
      id: "file7.txt",
    },
    {
      name: "file8.txt",
      meta: "80 KB",
      id: "file8.txt",
    },
    {
      name: "file9.txt",
      meta: "90 KB",
      id: "file9.txt",
    },
    {
      name: "file10.txt",
      meta: "100 KB",
      id: "file10.txt",
    },
  ],
  selectedRoomId: "1",
  isLoadingRoom: false,
  isLoadingMessage: false,
  isLoadingMoreRooms: false,
  isLoadingMoreMessages: false,
  inputMessage: "",
  roomActions: [
    {
      label: "Delete",
      value: "delete-room",
    },
  ],
  myMessageActions: [
    {
      label: "Edit",
      value: "edit-message",
    },
    {
      label: "Delete",
      value: "delete-message",
    },
  ],
  theirMessageActions: [
    {
      label: "Delete",
      value: "delete-message",
    },
  ],
  isMobile: false,
  isSingleRoom: false,
  isEmojiPickerAvailable: true,
  isEmojiReactionAvailable: true,
  isMessageAttachmentAvailable: true,
  isReplyAvailable: true,
  isMarkdownAvailable: true,
  isTyping: true,
  showRoomAvatar: false,
  showTheirAvatar: false,
  dialog: {
    event: "test",
    body: "This is a test dialog",
    leftButton: {
      text: "Cancel",
    },
    rightButton: {
      text: "OK",
      variant: "success",
    },
  },
  height: 600,
  i18n: {
    deletedMessage: "このメッセージは削除されました。",
    chatFooterTextareaPlaceholder: "メッセージを入力してください",
    chatSearchPlaceholder: "ルームを検索",
    closedRoomMessage: "このチャットは終了しました",
  },
  theme: "light",
};
