import {
  AdvancedChatKaiProps,
  ChatMessageAttachment,
  ChatMessageReply,
  ChatMessageSuggestion,
  Dialog,
  I18nType,
} from "../src/types";

export const testProps: AdvancedChatKaiProps = {
  currentUserId: "current-user-id",
  rooms: [
    {
      id: "room-1",
      headerTitle: "Room 1",
      headerSubtitle: "This is the first room",
      sidebarTitle: "Room 1",
      sidebarSubtitle: "This is the first room",
      avatar: "./lit.svg",
      meta: "June 1, 2025",
      hasEnded: false,
    },
    {
      id: "room-2",
      headerTitle: "Room 2",
      headerSubtitle: "This is the second room",
      sidebarTitle: "Room 2",
      sidebarSubtitle: "This is the second room",
      avatar: "./lit.svg",
      meta: "June 2, 2025",
      badge: {
        label: "Success",
        type: "success",
      },
      hasEnded: false,
    },
    {
      id: "room-3",
      headerTitle: "Room 3",
      headerSubtitle: "This is the third room",
      sidebarTitle: "Room 3",
      sidebarSubtitle: "This is the third room",
      avatar: "./lit.svg",
      meta: "June 3, 2025",
      badge: {
        label: "Info",
        type: "info",
      },
      hasEnded: false,
    },
    {
      id: "room-4",
      headerTitle: "Room 4",
      headerSubtitle: "This is the fourth room",
      sidebarTitle: "Room 4",
      sidebarSubtitle: "This is the fourth room",
      avatar: "./lit.svg",
      meta: "June 4, 2025",
      badge: {
        label: "Warning",
        type: "warning",
      },
      hasEnded: false,
    },
    {
      id: "room-5",
      headerTitle: "Room 5",
      headerSubtitle: "This is the fifth room",
      sidebarTitle: "Room 5",
      sidebarSubtitle: "This is the fifth room",
      avatar: "./lit.svg",
      meta: "June 5, 2025",
      badge: {
        label: "Danger",
        type: "danger",
      },
      hasEnded: false,
    },
    {
      id: "room-6",
      headerTitle: "Room 6",
      headerSubtitle: "This is the sixth room",
      sidebarTitle: "Room 6",
      sidebarSubtitle: "This is the sixth room",
      avatar: "./lit.svg",
      meta: "June 6, 2025",
      badge: {
        label: "",
        type: "success",
      },
      hasEnded: false,
    },
    {
      id: "room-7",
      headerTitle: "Room 7",
      headerSubtitle: "This is the seventh room",
      sidebarTitle: "Room 7",
      sidebarSubtitle: "This is the seventh room",
      avatar: "./lit.svg",
      meta: "June 7, 2025",
      badge: {
        label: "",
        type: "info",
      },
      hasEnded: false,
    },
    {
      id: "room-8",
      headerTitle: "Room 8",
      headerSubtitle: "This is the eighth room",
      sidebarTitle: "Room 8",
      sidebarSubtitle: "This is the eighth room",
      avatar: "./lit.svg",
      meta: "June 8, 2025",
      badge: {
        label: "",
        type: "warning",
      },
      hasEnded: false,
    },
    {
      id: "room-9",
      headerTitle: "Room 9",
      headerSubtitle: "This is the ninth room",
      sidebarTitle: "Room 9",
      sidebarSubtitle: "This is the ninth room",
      avatar: "./lit.svg",
      meta: "June 9, 2025",
      badge: {
        label: "",
        type: "danger",
      },
      hasEnded: false,
    },
  ],
  messages: [
    {
      id: "divider-1",
      type: "divider",
      roomId: "room-1",
      content: "June 1, 2025",
    },
    {
      id: "message-1",
      type: "message",
      roomId: "room-1",
      senderId: "user-1",
      senderName: "User 1",
      senderAvatar: "./lit.svg",
      content: "This is the first message",
      timestamp: "12:34 PM",
      reactions: new Map<string, Set<string>>([
        ["❤️", new Set(["user-1", "current-user-id"])],
        ["🔥", new Set(["user-1"])],
        ["👍", new Set(["current-user-id"])],
      ]),
      attachments: [],
      isDeleted: false,
      isSelected: false,
      replyTo: null,
    },
    {
      id: "message-2",
      type: "message",
      roomId: "room-1",
      senderId: "user-1",
      senderName: "User 1",
      senderAvatar: "./lit.svg",
      content: "This is the second message",
      timestamp: "12:35 PM",
      reactions: new Map(),
      attachments: [],
      isDeleted: false,
      isSelected: false,
      replyTo: null,
    },
    {
      id: "message-3",
      type: "message",
      roomId: "room-1",
      senderId: "current-user-id",
      senderName: "Current User",
      senderAvatar: "./lit.svg",
      content: "This is the third message",
      timestamp: "12:36 PM",
      reactions: new Map(),
      attachments: [],
      isDeleted: false,
      isSelected: false,
      replyTo: null,
    },
    {
      id: "message-4",
      type: "message",
      roomId: "room-1",
      senderId: "current-user-id",
      senderName: "Current User",
      senderAvatar: "./lit.svg",
      content: "This is the fourth message and reply to the second message",
      timestamp: "12:37 PM",
      reactions: new Map(),
      attachments: [],
      isDeleted: false,
      isSelected: false,
      replyTo: {
        id: "message-2",
        type: "message",
        roomId: "room-1",
        senderId: "user-1",
        senderName: "User 1",
        senderAvatar: "./lit.svg",
        content: "This is the second message",
        timestamp: "12:35 PM",
        reactions: new Map(),
        attachments: [],
        isDeleted: false,
        isSelected: false,
      },
    },
    {
      id: "message-5",
      type: "message",
      roomId: "room-1",
      senderId: "user-1",
      senderName: "User 1",
      senderAvatar: "./lit.svg",
      content: "This is the fifth message",
      timestamp: "12:38 PM",
      reactions: new Map(),
      attachments: [
        {
          id: "attachment-1",
          name: "file.txt",
          meta: "2 KB",
        },
        {
          id: "attachment-2",
          name: "image-1.png",
          meta: "1 MB",
          imageUrl: "./message-attachment-1.jpg",
        },
        {
          id: "attachment-3",
          name: "image-2.png",
          meta: "500 KB",
          imageUrl: "./message-attachment-2.jpg",
        },
      ],
      isDeleted: false,
      isSelected: false,
      replyTo: null,
    },
    {
      id: "message-6",
      type: "message",
      roomId: "room-1",
      senderId: "current-user-id",
      senderName: "Current User",
      senderAvatar: "./lit.svg",
      content: "This is the sixth message",
      timestamp: "12:39 PM",
      reactions: new Map(),
      attachments: [],
      isDeleted: true,
      isSelected: false,
      replyTo: null,
    },
    {
      id: "message-7",
      type: "message",
      roomId: "room-1",
      senderId: "current-user-id",
      senderName: "Current User",
      senderAvatar: "./lit.svg",
      content: "This is the seventh message and selected",
      timestamp: "12:40 PM",
      reactions: new Map(),
      attachments: [],
      isDeleted: false,
      isSelected: true,
      replyTo: null,
    },
  ],
  attachments: [],
  suggestions: [],
  replyTo: null,
  selectedRoomId: "room-1",
  isLoadingRoom: false,
  isLoadingMessage: false,
  isLoadingMoreRooms: false,
  isLoadingMoreMessages: false,
  inputMessage: "",
  roomActions: [
    {
      label: "Delete Room",
      value: "delete-room",
    },
  ],
  myMessageActions: [
    {
      label: "Edit Message",
      value: "edit-message",
    },
    {
      label: "Delete Message",
      value: "delete-message",
    },
  ],
  theirMessageActions: [],
  isMobile: false,
  isSingleRoom: false,
  isEmojiPickerAvailable: true,
  isEmojiReactionAvailable: true,
  isMessageAttachmentAvailable: true,
  isReplyAvailable: true,
  isMarkdownAvailable: true,
  isTyping: false,
  showRoomAvatar: true,
  showTheirAvatar: true,
  dialog: null,
  height: "60em",
  width: "80em",
  i18n: {},
  theme: "light",
};

export const testAttachments: ChatMessageAttachment[] = [
  {
    id: "attachment-1",
    name: "file.txt",
    meta: "2 KB",
  },
  {
    id: "attachment-2",
    name: "image-1.png",
    meta: "1 MB",
    imageUrl: "./message-attachment-1.jpg",
  },
  {
    id: "attachment-3",
    name: "image-2.png",
    meta: "500 KB",
    imageUrl: "./message-attachment-2.jpg",
  },
];

export const testDialog: Dialog = {
  event: "delete-room",
  body: "Are you sure you want to delete this room?",
  leftButton: {
    text: "Cancel",
  },
  rightButton: {
    text: "Delete",
    variant: "danger",
  },
};

export const testSuggestions: ChatMessageSuggestion[] = [
  {
    text: "This is the first suggestion",
    value: "suggestion-1",
  },
  {
    text: "This is the second suggestion",
    value: "suggestion-2",
  },
  {
    text: "This is the third suggestion",
    value: "suggestion-3",
  },
  {
    text: "This is the fourth suggestion",
    value: "suggestion-4",
  },
];

export const testReplyTo: ChatMessageReply = {
  id: "message-2",
  type: "message",
  roomId: "room-1",
  senderId: "user-1",
  senderName: "User 1",
  senderAvatar: "./lit.svg",
  content: "This is the second message",
  timestamp: "12:35 PM",
  reactions: new Map(),
  attachments: [],
  isDeleted: false,
  isSelected: false,
};

export const testI18n: I18nType = {
  DELETED_MESSAGE: "このメッセージは削除されました",
  CHAT_SEARCH_PLACEHOLDER: "チャットを検索",
  CHAT_FOOTER_TEXTAREA_PLACEHOLDER: "メッセージを入力...",
  CLOSED_ROOM_MESSAGE: "このルームは終了しました",
  NEW_MESSAGE_NOTIFICATION: "新しいメッセージがあります",
};
